// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlcdb

import (
	"context"
)

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO announcements (title, content_md, is_active)
VALUES ($1, $2, $3) RETURNING id, title, content_md, is_active, created_at
`

type CreateAnnouncementParams struct {
	Title     string `json:"title"`
	ContentMd string `json:"content_md"`
	IsActive  bool   `json:"is_active"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement, arg.Title, arg.ContentMd, arg.IsActive)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ContentMd,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, description)
VALUES ($1, $2) RETURNING id, name, description, created_at
`

type CreateGroupParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.Name, arg.Description)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
