// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO admin_audit_logs (admin_id, action, target_type, target_id, details, ip_address)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAuditLogParams struct {
	AdminID    int64  `json:"admin_id"`
	Action     string `json:"action"`
	TargetType string `json:"target_type"`
	TargetID   *int64 `json:"target_id"`
	Details    []byte `json:"details"`
	IpAddress  string `json:"ip_address"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.AdminID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Details,
		arg.IpAddress,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT al.id, al.admin_id, al.action, al.target_type, al.target_id, al.details, al.ip_address, al.created_at, u.username as admin_username
FROM admin_audit_logs al
JOIN users u ON u.id = al.admin_id
ORDER BY al.created_at DESC
LIMIT $2 OFFSET $1
`

type ListAuditLogsParams struct {
	OffsetVal int32 `json:"offset_val"`
	LimitVal  int32 `json:"limit_val"`
}

type ListAuditLogsRow struct {
	ID            int64              `json:"id"`
	AdminID       int64              `json:"admin_id"`
	Action        string             `json:"action"`
	TargetType    string             `json:"target_type"`
	TargetID      *int64             `json:"target_id"`
	Details       []byte             `json:"details"`
	IpAddress     string             `json:"ip_address"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	AdminUsername string             `json:"admin_username"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
			&i.AdminUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByAdmin = `-- name: ListAuditLogsByAdmin :many
SELECT id, admin_id, action, target_type, target_id, details, ip_address, created_at FROM admin_audit_logs WHERE admin_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListAuditLogsByAdminParams struct {
	AdminID   int64 `json:"admin_id"`
	OffsetVal int32 `json:"offset_val"`
	LimitVal  int32 `json:"limit_val"`
}

func (q *Queries) ListAuditLogsByAdmin(ctx context.Context, arg ListAuditLogsByAdminParams) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByAdmin, arg.AdminID, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAuditLog{}
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByTarget = `-- name: ListAuditLogsByTarget :many
SELECT id, admin_id, action, target_type, target_id, details, ip_address, created_at FROM admin_audit_logs WHERE target_type = $1 AND target_id = $2
ORDER BY created_at DESC
`

type ListAuditLogsByTargetParams struct {
	TargetType string `json:"target_type"`
	TargetID   *int64 `json:"target_id"`
}

func (q *Queries) ListAuditLogsByTarget(ctx context.Context, arg ListAuditLogsByTargetParams) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByTarget, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAuditLog{}
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
