// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blogs.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBlog = `-- name: CreateBlog :one
INSERT INTO blogs (title, slug, content_md, author_id, is_published)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateBlogParams struct {
	Title       string `json:"title"`
	Slug        string `json:"slug"`
	ContentMd   string `json:"content_md"`
	AuthorID    int64  `json:"author_id"`
	IsPublished bool   `json:"is_published"`
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (int64, error) {
	row := q.db.QueryRow(ctx, createBlog,
		arg.Title,
		arg.Slug,
		arg.ContentMd,
		arg.AuthorID,
		arg.IsPublished,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteBlog = `-- name: DeleteBlog :exec
DELETE FROM blogs WHERE id = $1
`

func (q *Queries) DeleteBlog(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBlog, id)
	return err
}

const getAllBlogsAdmin = `-- name: GetAllBlogsAdmin :many
SELECT blogs.id, blogs.author_id, blogs.title, blogs.content_md, blogs.created_at, blogs.slug, blogs.is_published, blogs.updated_at, users.username AS author_username
FROM blogs
JOIN users ON blogs.author_id = users.id
ORDER BY blogs.created_at DESC
`

type GetAllBlogsAdminRow struct {
	ID             int64              `json:"id"`
	AuthorID       int64              `json:"author_id"`
	Title          string             `json:"title"`
	ContentMd      string             `json:"content_md"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Slug           string             `json:"slug"`
	IsPublished    bool               `json:"is_published"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AuthorUsername string             `json:"author_username"`
}

func (q *Queries) GetAllBlogsAdmin(ctx context.Context) ([]GetAllBlogsAdminRow, error) {
	rows, err := q.db.Query(ctx, getAllBlogsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllBlogsAdminRow{}
	for rows.Next() {
		var i GetAllBlogsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.ContentMd,
			&i.CreatedAt,
			&i.Slug,
			&i.IsPublished,
			&i.UpdatedAt,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlogByIDAdmin = `-- name: GetBlogByIDAdmin :one
SELECT id, author_id, title, content_md, created_at, slug, is_published, updated_at FROM blogs WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBlogByIDAdmin(ctx context.Context, id int64) (Blog, error) {
	row := q.db.QueryRow(ctx, getBlogByIDAdmin, id)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.ContentMd,
		&i.CreatedAt,
		&i.Slug,
		&i.IsPublished,
		&i.UpdatedAt,
	)
	return i, err
}

const getBlogBySlug = `-- name: GetBlogBySlug :one
SELECT blogs.id, blogs.author_id, blogs.title, blogs.content_md, blogs.created_at, blogs.slug, blogs.is_published, blogs.updated_at, users.username AS author_username
FROM blogs
JOIN users ON blogs.author_id = users.id
WHERE blogs.slug = $1 LIMIT 1
`

type GetBlogBySlugRow struct {
	ID             int64              `json:"id"`
	AuthorID       int64              `json:"author_id"`
	Title          string             `json:"title"`
	ContentMd      string             `json:"content_md"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Slug           string             `json:"slug"`
	IsPublished    bool               `json:"is_published"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AuthorUsername string             `json:"author_username"`
}

func (q *Queries) GetBlogBySlug(ctx context.Context, slug string) (GetBlogBySlugRow, error) {
	row := q.db.QueryRow(ctx, getBlogBySlug, slug)
	var i GetBlogBySlugRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.ContentMd,
		&i.CreatedAt,
		&i.Slug,
		&i.IsPublished,
		&i.UpdatedAt,
		&i.AuthorUsername,
	)
	return i, err
}

const getBlogs = `-- name: GetBlogs :many
SELECT blogs.id, blogs.author_id, blogs.title, blogs.content_md, blogs.created_at, blogs.slug, blogs.is_published, blogs.updated_at, users.username AS author_username
FROM blogs
JOIN users ON blogs.author_id = users.id
WHERE is_published = true
ORDER BY blogs.created_at DESC
`

type GetBlogsRow struct {
	ID             int64              `json:"id"`
	AuthorID       int64              `json:"author_id"`
	Title          string             `json:"title"`
	ContentMd      string             `json:"content_md"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Slug           string             `json:"slug"`
	IsPublished    bool               `json:"is_published"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AuthorUsername string             `json:"author_username"`
}

func (q *Queries) GetBlogs(ctx context.Context) ([]GetBlogsRow, error) {
	rows, err := q.db.Query(ctx, getBlogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBlogsRow{}
	for rows.Next() {
		var i GetBlogsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.ContentMd,
			&i.CreatedAt,
			&i.Slug,
			&i.IsPublished,
			&i.UpdatedAt,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlog = `-- name: UpdateBlog :exec
UPDATE blogs
SET title = $2, slug = $3, content_md = $4, is_published = $5, updated_at = NOW()
WHERE id = $1
`

type UpdateBlogParams struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	Slug        string `json:"slug"`
	ContentMd   string `json:"content_md"`
	IsPublished bool   `json:"is_published"`
}

func (q *Queries) UpdateBlog(ctx context.Context, arg UpdateBlogParams) error {
	_, err := q.db.Exec(ctx, updateBlog,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.ContentMd,
		arg.IsPublished,
	)
	return err
}
