// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classes.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addClassMember = `-- name: AddClassMember :exec
INSERT INTO class_members (class_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (class_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type AddClassMemberParams struct {
	ClassID int64  `json:"class_id"`
	UserID  int64  `json:"user_id"`
	Role    string `json:"role"`
}

func (q *Queries) AddClassMember(ctx context.Context, arg AddClassMemberParams) error {
	_, err := q.db.Exec(ctx, addClassMember, arg.ClassID, arg.UserID, arg.Role)
	return err
}

const addContestToClass = `-- name: AddContestToClass :exec
INSERT INTO class_contests (class_id, contest_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddContestToClassParams struct {
	ClassID   int64 `json:"class_id"`
	ContestID int64 `json:"contest_id"`
}

func (q *Queries) AddContestToClass(ctx context.Context, arg AddContestToClassParams) error {
	_, err := q.db.Exec(ctx, addContestToClass, arg.ClassID, arg.ContestID)
	return err
}

const addProblemToClass = `-- name: AddProblemToClass :exec
INSERT INTO class_problems (class_id, problem_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddProblemToClassParams struct {
	ClassID   int64 `json:"class_id"`
	ProblemID int64 `json:"problem_id"`
}

func (q *Queries) AddProblemToClass(ctx context.Context, arg AddProblemToClassParams) error {
	_, err := q.db.Exec(ctx, addProblemToClass, arg.ClassID, arg.ProblemID)
	return err
}

const checkContestInClass = `-- name: CheckContestInClass :one
SELECT EXISTS (
    SELECT 1 FROM class_contests WHERE class_id = $1 AND contest_id = $2
)
`

type CheckContestInClassParams struct {
	ClassID   int64 `json:"class_id"`
	ContestID int64 `json:"contest_id"`
}

func (q *Queries) CheckContestInClass(ctx context.Context, arg CheckContestInClassParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkContestInClass, arg.ClassID, arg.ContestID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkProblemInClass = `-- name: CheckProblemInClass :one
SELECT EXISTS (
    SELECT 1 FROM class_problems WHERE class_id = $1 AND problem_id = $2
)
`

type CheckProblemInClassParams struct {
	ClassID   int64 `json:"class_id"`
	ProblemID int64 `json:"problem_id"`
}

func (q *Queries) CheckProblemInClass(ctx context.Context, arg CheckProblemInClassParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkProblemInClass, arg.ClassID, arg.ProblemID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createClass = `-- name: CreateClass :one
INSERT INTO classes (name, description, weekly_schedule, notice_md)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, schedule_md, notice_md, created_at, weekly_schedule
`

type CreateClassParams struct {
	Name           string `json:"name"`
	Description    string `json:"description"`
	WeeklySchedule []byte `json:"weekly_schedule"`
	NoticeMd       string `json:"notice_md"`
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, createClass,
		arg.Name,
		arg.Description,
		arg.WeeklySchedule,
		arg.NoticeMd,
	)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ScheduleMd,
		&i.NoticeMd,
		&i.CreatedAt,
		&i.WeeklySchedule,
	)
	return i, err
}

const getClassByID = `-- name: GetClassByID :one
SELECT id, name, description, schedule_md, notice_md, created_at, weekly_schedule FROM classes WHERE id = $1
`

func (q *Queries) GetClassByID(ctx context.Context, id int64) (Class, error) {
	row := q.db.QueryRow(ctx, getClassByID, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ScheduleMd,
		&i.NoticeMd,
		&i.CreatedAt,
		&i.WeeklySchedule,
	)
	return i, err
}

const getClassMembers = `-- name: GetClassMembers :many
SELECT u.id, u.username, u.display_name, cm.role, cm.created_at
FROM class_members cm
JOIN users u ON u.id = cm.user_id
WHERE cm.class_id = $1
ORDER BY (CASE WHEN cm.role = 'teacher' THEN 1 WHEN cm.role = 'student' THEN 2 ELSE 3 END), u.username
`

type GetClassMembersRow struct {
	ID          int64              `json:"id"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetClassMembers(ctx context.Context, classID int64) ([]GetClassMembersRow, error) {
	rows, err := q.db.Query(ctx, getClassMembers, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClassMembersRow{}
	for rows.Next() {
		var i GetClassMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClassesForContest = `-- name: GetClassesForContest :many
SELECT class_id FROM class_contests WHERE contest_id = $1
`

func (q *Queries) GetClassesForContest(ctx context.Context, contestID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getClassesForContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var class_id int64
		if err := rows.Scan(&class_id); err != nil {
			return nil, err
		}
		items = append(items, class_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClassesForProblem = `-- name: GetClassesForProblem :many
SELECT class_id FROM class_problems WHERE problem_id = $1
`

func (q *Queries) GetClassesForProblem(ctx context.Context, problemID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getClassesForProblem, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var class_id int64
		if err := rows.Scan(&class_id); err != nil {
			return nil, err
		}
		items = append(items, class_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserClasses = `-- name: GetUserClasses :many
SELECT c.id, c.name, c.description, c.schedule_md, c.notice_md, c.created_at, c.weekly_schedule, cm.role
FROM classes c
JOIN class_members cm ON cm.class_id = c.id
WHERE cm.user_id = $1
ORDER BY c.created_at DESC
`

type GetUserClassesRow struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	ScheduleMd     string             `json:"schedule_md"`
	NoticeMd       string             `json:"notice_md"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	WeeklySchedule []byte             `json:"weekly_schedule"`
	Role           string             `json:"role"`
}

func (q *Queries) GetUserClasses(ctx context.Context, userID int64) ([]GetUserClassesRow, error) {
	rows, err := q.db.Query(ctx, getUserClasses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserClassesRow{}
	for rows.Next() {
		var i GetUserClassesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ScheduleMd,
			&i.NoticeMd,
			&i.CreatedAt,
			&i.WeeklySchedule,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoleInClass = `-- name: GetUserRoleInClass :one
SELECT role FROM class_members WHERE class_id = $1 AND user_id = $2
`

type GetUserRoleInClassParams struct {
	ClassID int64 `json:"class_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) GetUserRoleInClass(ctx context.Context, arg GetUserRoleInClassParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserRoleInClass, arg.ClassID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listClassContests = `-- name: ListClassContests :many
SELECT c.id, c.title, c.start_at, c.end_at, c.created_at, c.ranking_type, c.is_hidden
FROM class_contests cc
JOIN contests c ON c.id = cc.contest_id
WHERE cc.class_id = $1
ORDER BY c.start_at DESC
`

func (q *Queries) ListClassContests(ctx context.Context, classID int64) ([]Contest, error) {
	rows, err := q.db.Query(ctx, listClassContests, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contest{}
	for rows.Next() {
		var i Contest
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.RankingType,
			&i.IsHidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassProblems = `-- name: ListClassProblems :many
SELECT p.id, p.slug, p.title, p.category, p.time_limit_ms, p.memory_limit_mb, p.created_at, p.is_hidden
FROM class_problems cp
JOIN problems p ON p.id = cp.problem_id
WHERE cp.class_id = $1
ORDER BY p.title
`

type ListClassProblemsRow struct {
	ID            int64              `json:"id"`
	Slug          string             `json:"slug"`
	Title         string             `json:"title"`
	Category      string             `json:"category"`
	TimeLimitMs   int32              `json:"time_limit_ms"`
	MemoryLimitMb int32              `json:"memory_limit_mb"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	IsHidden      bool               `json:"is_hidden"`
}

func (q *Queries) ListClassProblems(ctx context.Context, classID int64) ([]ListClassProblemsRow, error) {
	rows, err := q.db.Query(ctx, listClassProblems, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassProblemsRow{}
	for rows.Next() {
		var i ListClassProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Category,
			&i.TimeLimitMs,
			&i.MemoryLimitMb,
			&i.CreatedAt,
			&i.IsHidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClasses = `-- name: ListClasses :many
SELECT id, name, description, schedule_md, notice_md, created_at, weekly_schedule FROM classes ORDER BY created_at DESC
`

func (q *Queries) ListClasses(ctx context.Context) ([]Class, error) {
	rows, err := q.db.Query(ctx, listClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Class{}
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ScheduleMd,
			&i.NoticeMd,
			&i.CreatedAt,
			&i.WeeklySchedule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeClassMember = `-- name: RemoveClassMember :exec
DELETE FROM class_members WHERE class_id = $1 AND user_id = $2
`

type RemoveClassMemberParams struct {
	ClassID int64 `json:"class_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) RemoveClassMember(ctx context.Context, arg RemoveClassMemberParams) error {
	_, err := q.db.Exec(ctx, removeClassMember, arg.ClassID, arg.UserID)
	return err
}

const removeContestFromClass = `-- name: RemoveContestFromClass :exec
DELETE FROM class_contests WHERE class_id = $1 AND contest_id = $2
`

type RemoveContestFromClassParams struct {
	ClassID   int64 `json:"class_id"`
	ContestID int64 `json:"contest_id"`
}

func (q *Queries) RemoveContestFromClass(ctx context.Context, arg RemoveContestFromClassParams) error {
	_, err := q.db.Exec(ctx, removeContestFromClass, arg.ClassID, arg.ContestID)
	return err
}

const removeProblemFromClass = `-- name: RemoveProblemFromClass :exec
DELETE FROM class_problems WHERE class_id = $1 AND problem_id = $2
`

type RemoveProblemFromClassParams struct {
	ClassID   int64 `json:"class_id"`
	ProblemID int64 `json:"problem_id"`
}

func (q *Queries) RemoveProblemFromClass(ctx context.Context, arg RemoveProblemFromClassParams) error {
	_, err := q.db.Exec(ctx, removeProblemFromClass, arg.ClassID, arg.ProblemID)
	return err
}

const updateClass = `-- name: UpdateClass :exec
UPDATE classes SET name = $2, description = $3, weekly_schedule = $4, notice_md = $5 WHERE id = $1
`

type UpdateClassParams struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	Description    string `json:"description"`
	WeeklySchedule []byte `json:"weekly_schedule"`
	NoticeMd       string `json:"notice_md"`
}

func (q *Queries) UpdateClass(ctx context.Context, arg UpdateClassParams) error {
	_, err := q.db.Exec(ctx, updateClass,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.WeeklySchedule,
		arg.NoticeMd,
	)
	return err
}

const updateClassMemberRole = `-- name: UpdateClassMemberRole :exec
UPDATE class_members SET role = $3 WHERE class_id = $1 AND user_id = $2
`

type UpdateClassMemberRoleParams struct {
	ClassID int64  `json:"class_id"`
	UserID  int64  `json:"user_id"`
	Role    string `json:"role"`
}

func (q *Queries) UpdateClassMemberRole(ctx context.Context, arg UpdateClassMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateClassMemberRole, arg.ClassID, arg.UserID, arg.Role)
	return err
}
