// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contests.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addContestProblem = `-- name: AddContestProblem :exec
INSERT INTO contest_problems (contest_id, problem_id, label, points) VALUES ($1, $2, $3, $4)
`

type AddContestProblemParams struct {
	ContestID int64  `json:"contest_id"`
	ProblemID int64  `json:"problem_id"`
	Label     string `json:"label"`
	Points    int32  `json:"points"`
}

func (q *Queries) AddContestProblem(ctx context.Context, arg AddContestProblemParams) error {
	_, err := q.db.Exec(ctx, addContestProblem,
		arg.ContestID,
		arg.ProblemID,
		arg.Label,
		arg.Points,
	)
	return err
}

const calculateContestStandingsICPC = `-- name: CalculateContestStandingsICPC :many
WITH first_ac AS (
    SELECT
        s.user_id,
        s.problem_id,
        s.submitted_at AS ac_time,
        ROW_NUMBER() OVER (
            PARTITION BY s.user_id, s.problem_id
            ORDER BY s.submitted_at ASC
        ) AS rn
    FROM submissions s
    WHERE s.contest_id = $1
      AND s.score = 100
),
wrong_attempts AS (
    SELECT
        s.user_id,
        s.problem_id,
        COUNT(*) AS wrong_count
    FROM submissions s
    JOIN first_ac fa
        ON fa.user_id = s.user_id
       AND fa.problem_id = s.problem_id
       AND fa.rn = 1
    WHERE s.contest_id = $1
      AND s.submitted_at < fa.ac_time
      AND s.score < 100
    GROUP BY s.user_id, s.problem_id
)
SELECT
    u.id AS user_id,
    u.username,
    COUNT(DISTINCT fa.problem_id)::BIGINT AS solved_count,
    COALESCE(SUM(
        EXTRACT(EPOCH FROM (fa.ac_time - c.start_at))/60
        + 20 * COALESCE(wa.wrong_count, 0)
    ), 0)::BIGINT AS total_penalty_minutes
FROM first_ac fa
JOIN users u ON u.id = fa.user_id
JOIN contests c ON c.id = $1
LEFT JOIN wrong_attempts wa
    ON wa.user_id = fa.user_id AND wa.problem_id = fa.problem_id
WHERE fa.rn = 1
GROUP BY u.id, u.username
ORDER BY solved_count DESC, total_penalty_minutes ASC
`

type CalculateContestStandingsICPCRow struct {
	UserID              int64  `json:"user_id"`
	Username            string `json:"username"`
	SolvedCount         int64  `json:"solved_count"`
	TotalPenaltyMinutes int64  `json:"total_penalty_minutes"`
}

func (q *Queries) CalculateContestStandingsICPC(ctx context.Context, contestID int64) ([]CalculateContestStandingsICPCRow, error) {
	rows, err := q.db.Query(ctx, calculateContestStandingsICPC, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalculateContestStandingsICPCRow{}
	for rows.Next() {
		var i CalculateContestStandingsICPCRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.SolvedCount,
			&i.TotalPenaltyMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const calculateContestStandingsIOI = `-- name: CalculateContestStandingsIOI :many
WITH best_submissions AS (
    SELECT
        s.user_id,
        s.problem_id,
        s.score,
        s.submitted_at,
        ROW_NUMBER() OVER (
            PARTITION BY s.user_id, s.problem_id
            ORDER BY s.score DESC, s.submitted_at ASC
        ) AS rn
    FROM submissions s
    WHERE s.contest_id = $1
)
SELECT
    u.id AS user_id,
    u.username,
    COALESCE(SUM(bs.score), 0)::BIGINT AS total_score
FROM best_submissions bs
JOIN users u ON u.id = bs.user_id
JOIN contests c ON c.id = $1
WHERE bs.rn = 1
GROUP BY u.id, u.username
ORDER BY total_score DESC, username ASC
`

type CalculateContestStandingsIOIRow struct {
	UserID     int64  `json:"user_id"`
	Username   string `json:"username"`
	TotalScore int64  `json:"total_score"`
}

func (q *Queries) CalculateContestStandingsIOI(ctx context.Context, contestID int64) ([]CalculateContestStandingsIOIRow, error) {
	rows, err := q.db.Query(ctx, calculateContestStandingsIOI, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalculateContestStandingsIOIRow{}
	for rows.Next() {
		var i CalculateContestStandingsIOIRow
		if err := rows.Scan(&i.UserID, &i.Username, &i.TotalScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createContest = `-- name: CreateContest :one
INSERT INTO contests (title, start_at, end_at, ranking_type) VALUES ($1, $2, $3, $4) RETURNING id, title, start_at, end_at, created_at, ranking_type
`

type CreateContestParams struct {
	Title       string             `json:"title"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	RankingType string             `json:"ranking_type"`
}

func (q *Queries) CreateContest(ctx context.Context, arg CreateContestParams) (Contest, error) {
	row := q.db.QueryRow(ctx, createContest,
		arg.Title,
		arg.StartAt,
		arg.EndAt,
		arg.RankingType,
	)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.RankingType,
	)
	return i, err
}

const getContestByID = `-- name: GetContestByID :one
SELECT id, title, start_at, end_at, created_at, ranking_type FROM contests WHERE id = $1
`

func (q *Queries) GetContestByID(ctx context.Context, id int64) (Contest, error) {
	row := q.db.QueryRow(ctx, getContestByID, id)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.RankingType,
	)
	return i, err
}

const getContestProblem = `-- name: GetContestProblem :one
SELECT p.id, p.slug, p.title, p.category, p.time_limit_ms, p.memory_limit_mb, p.statement_md, p.input_desc, p.output_desc, p.constraints_desc, p.examples, p.checker_type, p.custom_checker_code, p.created_at, p.editorial_content, p.tags, p.testcase_visibility, p.mirror_from
FROM problems p
JOIN contest_problems cp ON cp.problem_id = p.id
WHERE cp.contest_id = $1 AND p.slug = $2
`

type GetContestProblemParams struct {
	ContestID int64  `json:"contest_id"`
	Slug      string `json:"slug"`
}

func (q *Queries) GetContestProblem(ctx context.Context, arg GetContestProblemParams) (Problem, error) {
	row := q.db.QueryRow(ctx, getContestProblem, arg.ContestID, arg.Slug)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Category,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.StatementMd,
		&i.InputDesc,
		&i.OutputDesc,
		&i.ConstraintsDesc,
		&i.Examples,
		&i.CheckerType,
		&i.CustomCheckerCode,
		&i.CreatedAt,
		&i.EditorialContent,
		&i.Tags,
		&i.TestcaseVisibility,
		&i.MirrorFrom,
	)
	return i, err
}

const listContestProblems = `-- name: ListContestProblems :many
SELECT cp.label, cp.points, p.id, p.slug, p.title, p.category, p.time_limit_ms, p.memory_limit_mb, p.statement_md, p.input_desc, p.output_desc, p.constraints_desc, p.examples, p.checker_type, p.custom_checker_code, p.created_at, p.editorial_content, p.tags, p.testcase_visibility, p.mirror_from FROM contest_problems cp JOIN problems p ON p.id = cp.problem_id WHERE cp.contest_id = $1 ORDER BY cp.label
`

type ListContestProblemsRow struct {
	Label              string             `json:"label"`
	Points             int32              `json:"points"`
	ID                 int64              `json:"id"`
	Slug               string             `json:"slug"`
	Title              string             `json:"title"`
	Category           string             `json:"category"`
	TimeLimitMs        int32              `json:"time_limit_ms"`
	MemoryLimitMb      int32              `json:"memory_limit_mb"`
	StatementMd        string             `json:"statement_md"`
	InputDesc          string             `json:"input_desc"`
	OutputDesc         string             `json:"output_desc"`
	ConstraintsDesc    string             `json:"constraints_desc"`
	Examples           []byte             `json:"examples"`
	CheckerType        string             `json:"checker_type"`
	CustomCheckerCode  string             `json:"custom_checker_code"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	EditorialContent   string             `json:"editorial_content"`
	Tags               []byte             `json:"tags"`
	TestcaseVisibility string             `json:"testcase_visibility"`
	MirrorFrom         string             `json:"mirror_from"`
}

func (q *Queries) ListContestProblems(ctx context.Context, contestID int64) ([]ListContestProblemsRow, error) {
	rows, err := q.db.Query(ctx, listContestProblems, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContestProblemsRow{}
	for rows.Next() {
		var i ListContestProblemsRow
		if err := rows.Scan(
			&i.Label,
			&i.Points,
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Category,
			&i.TimeLimitMs,
			&i.MemoryLimitMb,
			&i.StatementMd,
			&i.InputDesc,
			&i.OutputDesc,
			&i.ConstraintsDesc,
			&i.Examples,
			&i.CheckerType,
			&i.CustomCheckerCode,
			&i.CreatedAt,
			&i.EditorialContent,
			&i.Tags,
			&i.TestcaseVisibility,
			&i.MirrorFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContests = `-- name: ListContests :many
SELECT id, title, start_at, end_at, created_at, ranking_type FROM contests ORDER BY start_at DESC
`

func (q *Queries) ListContests(ctx context.Context) ([]Contest, error) {
	rows, err := q.db.Query(ctx, listContests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contest{}
	for rows.Next() {
		var i Contest
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.RankingType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeContestProblem = `-- name: RemoveContestProblem :exec
DELETE FROM contest_problems WHERE contest_id = $1 AND problem_id = $2
`

type RemoveContestProblemParams struct {
	ContestID int64 `json:"contest_id"`
	ProblemID int64 `json:"problem_id"`
}

func (q *Queries) RemoveContestProblem(ctx context.Context, arg RemoveContestProblemParams) error {
	_, err := q.db.Exec(ctx, removeContestProblem, arg.ContestID, arg.ProblemID)
	return err
}

const updateContest = `-- name: UpdateContest :exec
UPDATE contests SET title = $2, start_at = $3, end_at = $4, ranking_type = $5 WHERE id = $1
`

type UpdateContestParams struct {
	ID          int64              `json:"id"`
	Title       string             `json:"title"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	RankingType string             `json:"ranking_type"`
}

func (q *Queries) UpdateContest(ctx context.Context, arg UpdateContestParams) error {
	_, err := q.db.Exec(ctx, updateContest,
		arg.ID,
		arg.Title,
		arg.StartAt,
		arg.EndAt,
		arg.RankingType,
	)
	return err
}
