// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: judge_nodes.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJudgeNode = `-- name: CreateJudgeNode :one
INSERT INTO judge_nodes (name, base_url, api_key_encrypted, is_active, max_concurrent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, base_url, api_key_encrypted, is_active, supported_languages, max_concurrent, active_jobs, is_healthy, last_health_check_at, consecutive_failures, created_at
`

type CreateJudgeNodeParams struct {
	Name            string `json:"name"`
	BaseUrl         string `json:"base_url"`
	ApiKeyEncrypted string `json:"api_key_encrypted"`
	IsActive        bool   `json:"is_active"`
	MaxConcurrent   int32  `json:"max_concurrent"`
}

func (q *Queries) CreateJudgeNode(ctx context.Context, arg CreateJudgeNodeParams) (JudgeNode, error) {
	row := q.db.QueryRow(ctx, createJudgeNode,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyEncrypted,
		arg.IsActive,
		arg.MaxConcurrent,
	)
	var i JudgeNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEncrypted,
		&i.IsActive,
		&i.SupportedLanguages,
		&i.MaxConcurrent,
		&i.ActiveJobs,
		&i.IsHealthy,
		&i.LastHealthCheckAt,
		&i.ConsecutiveFailures,
		&i.CreatedAt,
	)
	return i, err
}

const decrementNodeActiveJobs = `-- name: DecrementNodeActiveJobs :exec
UPDATE judge_nodes SET active_jobs = GREATEST(active_jobs - 1, 0) WHERE id = $1
`

func (q *Queries) DecrementNodeActiveJobs(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementNodeActiveJobs, id)
	return err
}

const deleteJudgeNode = `-- name: DeleteJudgeNode :exec
DELETE FROM judge_nodes WHERE id = $1
`

func (q *Queries) DeleteJudgeNode(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteJudgeNode, id)
	return err
}

const getJudgeNodeByID = `-- name: GetJudgeNodeByID :one
SELECT id, name, base_url, api_key_encrypted, is_active, supported_languages, max_concurrent, active_jobs, is_healthy, last_health_check_at, consecutive_failures, created_at FROM judge_nodes WHERE id = $1
`

func (q *Queries) GetJudgeNodeByID(ctx context.Context, id int64) (JudgeNode, error) {
	row := q.db.QueryRow(ctx, getJudgeNodeByID, id)
	var i JudgeNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEncrypted,
		&i.IsActive,
		&i.SupportedLanguages,
		&i.MaxConcurrent,
		&i.ActiveJobs,
		&i.IsHealthy,
		&i.LastHealthCheckAt,
		&i.ConsecutiveFailures,
		&i.CreatedAt,
	)
	return i, err
}

const incrementNodeActiveJobs = `-- name: IncrementNodeActiveJobs :exec
UPDATE judge_nodes SET active_jobs = active_jobs + 1 WHERE id = $1
`

func (q *Queries) IncrementNodeActiveJobs(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementNodeActiveJobs, id)
	return err
}

const listActiveHealthyNodes = `-- name: ListActiveHealthyNodes :many
SELECT id, name, base_url, api_key_encrypted, is_active, supported_languages, max_concurrent, active_jobs, is_healthy, last_health_check_at, consecutive_failures, created_at FROM judge_nodes WHERE is_active = true AND is_healthy = true ORDER BY id
`

func (q *Queries) ListActiveHealthyNodes(ctx context.Context) ([]JudgeNode, error) {
	rows, err := q.db.Query(ctx, listActiveHealthyNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JudgeNode{}
	for rows.Next() {
		var i JudgeNode
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKeyEncrypted,
			&i.IsActive,
			&i.SupportedLanguages,
			&i.MaxConcurrent,
			&i.ActiveJobs,
			&i.IsHealthy,
			&i.LastHealthCheckAt,
			&i.ConsecutiveFailures,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHealthyNodesForLanguage = `-- name: ListHealthyNodesForLanguage :many
SELECT id, name, base_url, api_key_encrypted, is_active, supported_languages, max_concurrent, active_jobs, is_healthy, last_health_check_at, consecutive_failures, created_at FROM judge_nodes WHERE is_active = true AND is_healthy = true AND supported_languages->>$1 = 'true'
`

func (q *Queries) ListHealthyNodesForLanguage(ctx context.Context, language []byte) ([]JudgeNode, error) {
	rows, err := q.db.Query(ctx, listHealthyNodesForLanguage, language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JudgeNode{}
	for rows.Next() {
		var i JudgeNode
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKeyEncrypted,
			&i.IsActive,
			&i.SupportedLanguages,
			&i.MaxConcurrent,
			&i.ActiveJobs,
			&i.IsHealthy,
			&i.LastHealthCheckAt,
			&i.ConsecutiveFailures,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJudgeNodes = `-- name: ListJudgeNodes :many
SELECT id, name, base_url, api_key_encrypted, is_active, supported_languages, max_concurrent, active_jobs, is_healthy, last_health_check_at, consecutive_failures, created_at FROM judge_nodes ORDER BY id
`

func (q *Queries) ListJudgeNodes(ctx context.Context) ([]JudgeNode, error) {
	rows, err := q.db.Query(ctx, listJudgeNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JudgeNode{}
	for rows.Next() {
		var i JudgeNode
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKeyEncrypted,
			&i.IsActive,
			&i.SupportedLanguages,
			&i.MaxConcurrent,
			&i.ActiveJobs,
			&i.IsHealthy,
			&i.LastHealthCheckAt,
			&i.ConsecutiveFailures,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleJudgeNodeActive = `-- name: ToggleJudgeNodeActive :exec
UPDATE judge_nodes SET is_active = NOT is_active WHERE id = $1
`

func (q *Queries) ToggleJudgeNodeActive(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, toggleJudgeNodeActive, id)
	return err
}

const updateJudgeNode = `-- name: UpdateJudgeNode :exec
UPDATE judge_nodes SET name = $2, base_url = $3, api_key_encrypted = $4, is_active = $5, max_concurrent = $6 WHERE id = $1
`

type UpdateJudgeNodeParams struct {
	ID              int64  `json:"id"`
	Name            string `json:"name"`
	BaseUrl         string `json:"base_url"`
	ApiKeyEncrypted string `json:"api_key_encrypted"`
	IsActive        bool   `json:"is_active"`
	MaxConcurrent   int32  `json:"max_concurrent"`
}

func (q *Queries) UpdateJudgeNode(ctx context.Context, arg UpdateJudgeNodeParams) error {
	_, err := q.db.Exec(ctx, updateJudgeNode,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyEncrypted,
		arg.IsActive,
		arg.MaxConcurrent,
	)
	return err
}

const updateJudgeNodeHealth = `-- name: UpdateJudgeNodeHealth :exec
UPDATE judge_nodes SET is_healthy = $2, supported_languages = $3, max_concurrent = $4,
    last_health_check_at = $5, consecutive_failures = $6 WHERE id = $1
`

type UpdateJudgeNodeHealthParams struct {
	ID                  int64              `json:"id"`
	IsHealthy           bool               `json:"is_healthy"`
	SupportedLanguages  []byte             `json:"supported_languages"`
	MaxConcurrent       int32              `json:"max_concurrent"`
	LastHealthCheckAt   pgtype.Timestamptz `json:"last_health_check_at"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
}

func (q *Queries) UpdateJudgeNodeHealth(ctx context.Context, arg UpdateJudgeNodeHealthParams) error {
	_, err := q.db.Exec(ctx, updateJudgeNodeHealth,
		arg.ID,
		arg.IsHealthy,
		arg.SupportedLanguages,
		arg.MaxConcurrent,
		arg.LastHealthCheckAt,
		arg.ConsecutiveFailures,
	)
	return err
}
