// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAuditLog struct {
	ID         int64              `json:"id"`
	AdminID    int64              `json:"admin_id"`
	Action     string             `json:"action"`
	TargetType string             `json:"target_type"`
	TargetID   *int64             `json:"target_id"`
	Details    []byte             `json:"details"`
	IpAddress  string             `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Announcement struct {
	ID        int64              `json:"id"`
	Title     string             `json:"title"`
	ContentMd string             `json:"content_md"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Blog struct {
	ID          int64              `json:"id"`
	AuthorID    int64              `json:"author_id"`
	Title       string             `json:"title"`
	ContentMd   string             `json:"content_md"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Slug        string             `json:"slug"`
	IsPublished bool               `json:"is_published"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Contest struct {
	ID          int64              `json:"id"`
	Title       string             `json:"title"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	RankingType string             `json:"ranking_type"`
}

type ContestProblem struct {
	ContestID int64  `json:"contest_id"`
	ProblemID int64  `json:"problem_id"`
	Label     string `json:"label"`
	Points    int32  `json:"points"`
}

type Group struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type GroupMember struct {
	GroupID int64  `json:"group_id"`
	UserID  int64  `json:"user_id"`
	Role    string `json:"role"`
}

type JudgeNode struct {
	ID                  int64              `json:"id"`
	Name                string             `json:"name"`
	BaseUrl             string             `json:"base_url"`
	ApiKeyEncrypted     string             `json:"api_key_encrypted"`
	IsActive            bool               `json:"is_active"`
	SupportedLanguages  []byte             `json:"supported_languages"`
	MaxConcurrent       int32              `json:"max_concurrent"`
	ActiveJobs          int32              `json:"active_jobs"`
	IsHealthy           bool               `json:"is_healthy"`
	LastHealthCheckAt   pgtype.Timestamptz `json:"last_health_check_at"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	IsLocal             bool               `json:"is_local"`
}

type Problem struct {
	ID                 int64              `json:"id"`
	Slug               string             `json:"slug"`
	Title              string             `json:"title"`
	Category           string             `json:"category"`
	TimeLimitMs        int32              `json:"time_limit_ms"`
	MemoryLimitMb      int32              `json:"memory_limit_mb"`
	StatementMd        string             `json:"statement_md"`
	InputDesc          string             `json:"input_desc"`
	OutputDesc         string             `json:"output_desc"`
	ConstraintsDesc    string             `json:"constraints_desc"`
	Examples           []byte             `json:"examples"`
	CheckerType        string             `json:"checker_type"`
	CustomCheckerCode  string             `json:"custom_checker_code"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	EditorialContent   string             `json:"editorial_content"`
	Tags               []byte             `json:"tags"`
	TestcaseVisibility string             `json:"testcase_visibility"`
	MirrorFrom         string             `json:"mirror_from"`
}

type Session struct {
	Token  string             `json:"token"`
	Data   []byte             `json:"data"`
	Expiry pgtype.Timestamptz `json:"expiry"`
}

type Submission struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	ProblemID     int64              `json:"problem_id"`
	Language      string             `json:"language"`
	SourceCode    string             `json:"source_code"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	Status        string             `json:"status"`
	Verdict       string             `json:"verdict"`
	CompileOutput string             `json:"compile_output"`
	TimeMs        int32              `json:"time_ms"`
	MemoryKb      int32              `json:"memory_kb"`
	CodeSize      int32              `json:"code_size"`
	RunAllTests   bool               `json:"run_all_tests"`
	JudgeNodeID   *int64             `json:"judge_node_id"`
	Attempts      int32              `json:"attempts"`
	ContestID     *int64             `json:"contest_id"`
	Score         int32              `json:"score"`
}

type SubmissionTestResult struct {
	ID           int64  `json:"id"`
	SubmissionID int64  `json:"submission_id"`
	TestIndex    int32  `json:"test_index"`
	Verdict      string `json:"verdict"`
	TimeMs       int32  `json:"time_ms"`
	MemoryKb     int32  `json:"memory_kb"`
	Stdout       string `json:"stdout"`
	Stderr       string `json:"stderr"`
	VszKb        int32  `json:"vsz_kb"`
}

type Subtask struct {
	ID           int64  `json:"id"`
	ProblemID    int64  `json:"problem_id"`
	SubtaskIndex int32  `json:"subtask_index"`
	Points       int32  `json:"points"`
	Description  string `json:"description"`
}

type TestCase struct {
	ID             int64   `json:"id"`
	ProblemID      int64   `json:"problem_id"`
	OrderIndex     int32   `json:"order_index"`
	Input          string  `json:"input"`
	ExpectedOutput string  `json:"expected_output"`
	IsSample       bool    `json:"is_sample"`
	SubtaskID      *int64  `json:"subtask_id"`
	Description    *string `json:"description"`
}

type User struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	Country      string             `json:"country"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
