// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: problems.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProblem = `-- name: CreateProblem :one
INSERT INTO problems (slug, title, category, time_limit_ms, memory_limit_mb, statement_md, input_desc, output_desc, constraints_desc, examples, checker_type, custom_checker_code, editorial_content, tags, testcase_visibility, mirror_from)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, slug, title, category, time_limit_ms, memory_limit_mb, statement_md, input_desc, output_desc, constraints_desc, examples, checker_type, custom_checker_code, created_at, editorial_content, tags, testcase_visibility, mirror_from
`

type CreateProblemParams struct {
	Slug               string `json:"slug"`
	Title              string `json:"title"`
	Category           string `json:"category"`
	TimeLimitMs        int32  `json:"time_limit_ms"`
	MemoryLimitMb      int32  `json:"memory_limit_mb"`
	StatementMd        string `json:"statement_md"`
	InputDesc          string `json:"input_desc"`
	OutputDesc         string `json:"output_desc"`
	ConstraintsDesc    string `json:"constraints_desc"`
	Examples           []byte `json:"examples"`
	CheckerType        string `json:"checker_type"`
	CustomCheckerCode  string `json:"custom_checker_code"`
	EditorialContent   string `json:"editorial_content"`
	Tags               []byte `json:"tags"`
	TestcaseVisibility string `json:"testcase_visibility"`
	MirrorFrom         string `json:"mirror_from"`
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (Problem, error) {
	row := q.db.QueryRow(ctx, createProblem,
		arg.Slug,
		arg.Title,
		arg.Category,
		arg.TimeLimitMs,
		arg.MemoryLimitMb,
		arg.StatementMd,
		arg.InputDesc,
		arg.OutputDesc,
		arg.ConstraintsDesc,
		arg.Examples,
		arg.CheckerType,
		arg.CustomCheckerCode,
		arg.EditorialContent,
		arg.Tags,
		arg.TestcaseVisibility,
		arg.MirrorFrom,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Category,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.StatementMd,
		&i.InputDesc,
		&i.OutputDesc,
		&i.ConstraintsDesc,
		&i.Examples,
		&i.CheckerType,
		&i.CustomCheckerCode,
		&i.CreatedAt,
		&i.EditorialContent,
		&i.Tags,
		&i.TestcaseVisibility,
		&i.MirrorFrom,
	)
	return i, err
}

const deleteProblem = `-- name: DeleteProblem :exec
DELETE FROM problems WHERE id = $1
`

func (q *Queries) DeleteProblem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProblem, id)
	return err
}

const getProblemByID = `-- name: GetProblemByID :one
SELECT id, slug, title, category, time_limit_ms, memory_limit_mb, statement_md, input_desc, output_desc, constraints_desc, examples, checker_type, custom_checker_code, created_at, editorial_content, tags, testcase_visibility, mirror_from FROM problems WHERE id = $1
`

func (q *Queries) GetProblemByID(ctx context.Context, id int64) (Problem, error) {
	row := q.db.QueryRow(ctx, getProblemByID, id)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Category,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.StatementMd,
		&i.InputDesc,
		&i.OutputDesc,
		&i.ConstraintsDesc,
		&i.Examples,
		&i.CheckerType,
		&i.CustomCheckerCode,
		&i.CreatedAt,
		&i.EditorialContent,
		&i.Tags,
		&i.TestcaseVisibility,
		&i.MirrorFrom,
	)
	return i, err
}

const getProblemBySlug = `-- name: GetProblemBySlug :one
SELECT id, slug, title, category, time_limit_ms, memory_limit_mb, statement_md, input_desc, output_desc, constraints_desc, examples, checker_type, custom_checker_code, created_at, editorial_content, tags, testcase_visibility, mirror_from FROM problems WHERE slug = $1
`

func (q *Queries) GetProblemBySlug(ctx context.Context, slug string) (Problem, error) {
	row := q.db.QueryRow(ctx, getProblemBySlug, slug)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Category,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.StatementMd,
		&i.InputDesc,
		&i.OutputDesc,
		&i.ConstraintsDesc,
		&i.Examples,
		&i.CheckerType,
		&i.CustomCheckerCode,
		&i.CreatedAt,
		&i.EditorialContent,
		&i.Tags,
		&i.TestcaseVisibility,
		&i.MirrorFrom,
	)
	return i, err
}

const getProblemCategories = `-- name: GetProblemCategories :many
SELECT DISTINCT category FROM problems ORDER BY category
`

func (q *Queries) GetProblemCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getProblemCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblems = `-- name: ListProblems :many
SELECT id, slug, title, category, time_limit_ms, memory_limit_mb, statement_md, input_desc, output_desc, constraints_desc, examples, checker_type, custom_checker_code, created_at, editorial_content, tags, testcase_visibility, mirror_from FROM problems ORDER BY category, title
`

func (q *Queries) ListProblems(ctx context.Context) ([]Problem, error) {
	rows, err := q.db.Query(ctx, listProblems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Problem{}
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Category,
			&i.TimeLimitMs,
			&i.MemoryLimitMb,
			&i.StatementMd,
			&i.InputDesc,
			&i.OutputDesc,
			&i.ConstraintsDesc,
			&i.Examples,
			&i.CheckerType,
			&i.CustomCheckerCode,
			&i.CreatedAt,
			&i.EditorialContent,
			&i.Tags,
			&i.TestcaseVisibility,
			&i.MirrorFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemsByCategory = `-- name: ListProblemsByCategory :many
SELECT id, slug, title, category, time_limit_ms, memory_limit_mb, statement_md, input_desc, output_desc, constraints_desc, examples, checker_type, custom_checker_code, created_at, editorial_content, tags, testcase_visibility, mirror_from FROM problems WHERE category = $1 ORDER BY title
`

func (q *Queries) ListProblemsByCategory(ctx context.Context, category string) ([]Problem, error) {
	rows, err := q.db.Query(ctx, listProblemsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Problem{}
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Category,
			&i.TimeLimitMs,
			&i.MemoryLimitMb,
			&i.StatementMd,
			&i.InputDesc,
			&i.OutputDesc,
			&i.ConstraintsDesc,
			&i.Examples,
			&i.CheckerType,
			&i.CustomCheckerCode,
			&i.CreatedAt,
			&i.EditorialContent,
			&i.Tags,
			&i.TestcaseVisibility,
			&i.MirrorFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProblems = `-- name: SearchProblems :many
SELECT p.id, p.slug, p.title, p.category, p.time_limit_ms, p.memory_limit_mb, p.statement_md, p.input_desc, p.output_desc, p.constraints_desc, p.examples, p.checker_type, p.custom_checker_code, p.created_at, p.editorial_content, p.tags, p.testcase_visibility, p.mirror_from,
  (
    SELECT s.verdict
    FROM submissions s
    WHERE s.problem_id = p.id
      AND s.user_id = $1
    ORDER BY (CASE WHEN s.verdict = 'AC' THEN 1 ELSE 2 END), s.submitted_at DESC
    LIMIT 1
  ) AS user_status
FROM problems p
WHERE
  ($2::text = '' OR p.title ILIKE '%' || $2 || '%' OR p.slug ILIKE '%' || $2 || '%' OR p.id::text = $2)
  AND ($3::text = '' OR p.category = $3)
ORDER BY p.category, p.title
`

type SearchProblemsParams struct {
	UserID      *int64 `json:"user_id"`
	SearchQuery string `json:"search_query"`
	Category    string `json:"category"`
}

type SearchProblemsRow struct {
	ID                 int64              `json:"id"`
	Slug               string             `json:"slug"`
	Title              string             `json:"title"`
	Category           string             `json:"category"`
	TimeLimitMs        int32              `json:"time_limit_ms"`
	MemoryLimitMb      int32              `json:"memory_limit_mb"`
	StatementMd        string             `json:"statement_md"`
	InputDesc          string             `json:"input_desc"`
	OutputDesc         string             `json:"output_desc"`
	ConstraintsDesc    string             `json:"constraints_desc"`
	Examples           []byte             `json:"examples"`
	CheckerType        string             `json:"checker_type"`
	CustomCheckerCode  string             `json:"custom_checker_code"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	EditorialContent   string             `json:"editorial_content"`
	Tags               []byte             `json:"tags"`
	TestcaseVisibility string             `json:"testcase_visibility"`
	MirrorFrom         string             `json:"mirror_from"`
	UserStatus         string             `json:"user_status"`
}

func (q *Queries) SearchProblems(ctx context.Context, arg SearchProblemsParams) ([]SearchProblemsRow, error) {
	rows, err := q.db.Query(ctx, searchProblems, arg.UserID, arg.SearchQuery, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProblemsRow{}
	for rows.Next() {
		var i SearchProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Category,
			&i.TimeLimitMs,
			&i.MemoryLimitMb,
			&i.StatementMd,
			&i.InputDesc,
			&i.OutputDesc,
			&i.ConstraintsDesc,
			&i.Examples,
			&i.CheckerType,
			&i.CustomCheckerCode,
			&i.CreatedAt,
			&i.EditorialContent,
			&i.Tags,
			&i.TestcaseVisibility,
			&i.MirrorFrom,
			&i.UserStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProblem = `-- name: UpdateProblem :exec
UPDATE problems SET title = $2, slug = $3, category = $4, time_limit_ms = $5, memory_limit_mb = $6,
    statement_md = $7, input_desc = $8, output_desc = $9, constraints_desc = $10,
    examples = $11, checker_type = $12, custom_checker_code = $13, editorial_content = $14,
    tags = $15, testcase_visibility = $16, mirror_from = $17
WHERE id = $1
`

type UpdateProblemParams struct {
	ID                 int64  `json:"id"`
	Title              string `json:"title"`
	Slug               string `json:"slug"`
	Category           string `json:"category"`
	TimeLimitMs        int32  `json:"time_limit_ms"`
	MemoryLimitMb      int32  `json:"memory_limit_mb"`
	StatementMd        string `json:"statement_md"`
	InputDesc          string `json:"input_desc"`
	OutputDesc         string `json:"output_desc"`
	ConstraintsDesc    string `json:"constraints_desc"`
	Examples           []byte `json:"examples"`
	CheckerType        string `json:"checker_type"`
	CustomCheckerCode  string `json:"custom_checker_code"`
	EditorialContent   string `json:"editorial_content"`
	Tags               []byte `json:"tags"`
	TestcaseVisibility string `json:"testcase_visibility"`
	MirrorFrom         string `json:"mirror_from"`
}

func (q *Queries) UpdateProblem(ctx context.Context, arg UpdateProblemParams) error {
	_, err := q.db.Exec(ctx, updateProblem,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Category,
		arg.TimeLimitMs,
		arg.MemoryLimitMb,
		arg.StatementMd,
		arg.InputDesc,
		arg.OutputDesc,
		arg.ConstraintsDesc,
		arg.Examples,
		arg.CheckerType,
		arg.CustomCheckerCode,
		arg.EditorialContent,
		arg.Tags,
		arg.TestcaseVisibility,
		arg.MirrorFrom,
	)
	return err
}
