// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submissions.sql

package sqlcdb

import (
	"context"
)

const countSubmissionsByProblem = `-- name: CountSubmissionsByProblem :one
SELECT COUNT(*) FROM submissions WHERE problem_id = $1
`

func (q *Queries) CountSubmissionsByProblem(ctx context.Context, problemID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSubmissionsByProblem, problemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (user_id, problem_id, contest_id, language, source_code, code_size, run_all_tests, score)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, problem_id, language, source_code, submitted_at, status, verdict, compile_output, time_ms, memory_kb, code_size, run_all_tests, judge_node_id, attempts, contest_id, score
`

type CreateSubmissionParams struct {
	UserID      int64  `json:"user_id"`
	ProblemID   int64  `json:"problem_id"`
	ContestID   *int64 `json:"contest_id"`
	Language    string `json:"language"`
	SourceCode  string `json:"source_code"`
	CodeSize    int32  `json:"code_size"`
	RunAllTests bool   `json:"run_all_tests"`
	Score       int32  `json:"score"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.UserID,
		arg.ProblemID,
		arg.ContestID,
		arg.Language,
		arg.SourceCode,
		arg.CodeSize,
		arg.RunAllTests,
		arg.Score,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.Language,
		&i.SourceCode,
		&i.SubmittedAt,
		&i.Status,
		&i.Verdict,
		&i.CompileOutput,
		&i.TimeMs,
		&i.MemoryKb,
		&i.CodeSize,
		&i.RunAllTests,
		&i.JudgeNodeID,
		&i.Attempts,
		&i.ContestID,
		&i.Score,
	)
	return i, err
}

const dequeueSubmission = `-- name: DequeueSubmission :one
WITH next AS (
    SELECT id FROM submissions
    WHERE status = 'queued'
    ORDER BY submitted_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE submissions SET status = 'dispatched', attempts = attempts + 1
FROM next WHERE submissions.id = next.id
RETURNING submissions.id, submissions.user_id, submissions.problem_id, submissions.language, submissions.source_code, submissions.submitted_at, submissions.status, submissions.verdict, submissions.compile_output, submissions.time_ms, submissions.memory_kb, submissions.code_size, submissions.run_all_tests, submissions.judge_node_id, submissions.attempts, submissions.contest_id, submissions.score
`

func (q *Queries) DequeueSubmission(ctx context.Context) (Submission, error) {
	row := q.db.QueryRow(ctx, dequeueSubmission)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.Language,
		&i.SourceCode,
		&i.SubmittedAt,
		&i.Status,
		&i.Verdict,
		&i.CompileOutput,
		&i.TimeMs,
		&i.MemoryKb,
		&i.CodeSize,
		&i.RunAllTests,
		&i.JudgeNodeID,
		&i.Attempts,
		&i.ContestID,
		&i.Score,
	)
	return i, err
}

const getContestSubmissions = `-- name: GetContestSubmissions :many
SELECT id, user_id, problem_id, language, source_code, submitted_at, status, verdict, compile_output, time_ms, memory_kb, code_size, run_all_tests, judge_node_id, attempts, contest_id, score FROM submissions
WHERE contest_id = $1 AND user_id = $2
ORDER BY submitted_at DESC
`

type GetContestSubmissionsParams struct {
	ContestID *int64 `json:"contest_id"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) GetContestSubmissions(ctx context.Context, arg GetContestSubmissionsParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, getContestSubmissions, arg.ContestID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.Language,
			&i.SourceCode,
			&i.SubmittedAt,
			&i.Status,
			&i.Verdict,
			&i.CompileOutput,
			&i.TimeMs,
			&i.MemoryKb,
			&i.CodeSize,
			&i.RunAllTests,
			&i.JudgeNodeID,
			&i.Attempts,
			&i.ContestID,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingSubmissionByUser = `-- name: GetPendingSubmissionByUser :one
SELECT id, user_id, problem_id, language, source_code, submitted_at, status, verdict, compile_output, time_ms, memory_kb, code_size, run_all_tests, judge_node_id, attempts, contest_id, score FROM submissions WHERE user_id = $1 AND problem_id = $2 AND status IN ('queued', 'dispatched', 'judging') LIMIT 1
`

type GetPendingSubmissionByUserParams struct {
	UserID    int64 `json:"user_id"`
	ProblemID int64 `json:"problem_id"`
}

func (q *Queries) GetPendingSubmissionByUser(ctx context.Context, arg GetPendingSubmissionByUserParams) (Submission, error) {
	row := q.db.QueryRow(ctx, getPendingSubmissionByUser, arg.UserID, arg.ProblemID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.Language,
		&i.SourceCode,
		&i.SubmittedAt,
		&i.Status,
		&i.Verdict,
		&i.CompileOutput,
		&i.TimeMs,
		&i.MemoryKb,
		&i.CodeSize,
		&i.RunAllTests,
		&i.JudgeNodeID,
		&i.Attempts,
		&i.ContestID,
		&i.Score,
	)
	return i, err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, user_id, problem_id, language, source_code, submitted_at, status, verdict, compile_output, time_ms, memory_kb, code_size, run_all_tests, judge_node_id, attempts, contest_id, score FROM submissions WHERE id = $1
`

func (q *Queries) GetSubmissionByID(ctx context.Context, id int64) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.Language,
		&i.SourceCode,
		&i.SubmittedAt,
		&i.Status,
		&i.Verdict,
		&i.CompileOutput,
		&i.TimeMs,
		&i.MemoryKb,
		&i.CodeSize,
		&i.RunAllTests,
		&i.JudgeNodeID,
		&i.Attempts,
		&i.ContestID,
		&i.Score,
	)
	return i, err
}

const getUserSolvedProblems = `-- name: GetUserSolvedProblems :many
SELECT DISTINCT problem_id FROM submissions WHERE user_id = $1 AND verdict = 'AC'
`

func (q *Queries) GetUserSolvedProblems(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getUserSolvedProblems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var problem_id int64
		if err := rows.Scan(&problem_id); err != nil {
			return nil, err
		}
		items = append(items, problem_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUserSolvedProblem = `-- name: HasUserSolvedProblem :one
SELECT EXISTS(SELECT 1 FROM submissions WHERE user_id = $1 AND problem_id = $2 AND verdict = 'AC')
`

type HasUserSolvedProblemParams struct {
	UserID    int64 `json:"user_id"`
	ProblemID int64 `json:"problem_id"`
}

func (q *Queries) HasUserSolvedProblem(ctx context.Context, arg HasUserSolvedProblemParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserSolvedProblem, arg.UserID, arg.ProblemID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAllSubmissions = `-- name: ListAllSubmissions :many
SELECT id, user_id, problem_id, language, source_code, submitted_at, status, verdict, compile_output, time_ms, memory_kb, code_size, run_all_tests, judge_node_id, attempts, contest_id, score FROM submissions ORDER BY submitted_at DESC LIMIT $2 OFFSET $1
`

type ListAllSubmissionsParams struct {
	OffsetVal int32 `json:"offset_val"`
	LimitVal  int32 `json:"limit_val"`
}

func (q *Queries) ListAllSubmissions(ctx context.Context, arg ListAllSubmissionsParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listAllSubmissions, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.Language,
			&i.SourceCode,
			&i.SubmittedAt,
			&i.Status,
			&i.Verdict,
			&i.CompileOutput,
			&i.TimeMs,
			&i.MemoryKb,
			&i.CodeSize,
			&i.RunAllTests,
			&i.JudgeNodeID,
			&i.Attempts,
			&i.ContestID,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByProblem = `-- name: ListSubmissionsByProblem :many
SELECT id, user_id, problem_id, language, source_code, submitted_at, status, verdict, compile_output, time_ms, memory_kb, code_size, run_all_tests, judge_node_id, attempts, contest_id, score FROM submissions WHERE problem_id = $1 ORDER BY submitted_at DESC LIMIT $3 OFFSET $2
`

type ListSubmissionsByProblemParams struct {
	ProblemID int64 `json:"problem_id"`
	OffsetVal int32 `json:"offset_val"`
	LimitVal  int32 `json:"limit_val"`
}

func (q *Queries) ListSubmissionsByProblem(ctx context.Context, arg ListSubmissionsByProblemParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByProblem, arg.ProblemID, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.Language,
			&i.SourceCode,
			&i.SubmittedAt,
			&i.Status,
			&i.Verdict,
			&i.CompileOutput,
			&i.TimeMs,
			&i.MemoryKb,
			&i.CodeSize,
			&i.RunAllTests,
			&i.JudgeNodeID,
			&i.Attempts,
			&i.ContestID,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByUser = `-- name: ListSubmissionsByUser :many
SELECT id, user_id, problem_id, language, source_code, submitted_at, status, verdict, compile_output, time_ms, memory_kb, code_size, run_all_tests, judge_node_id, attempts, contest_id, score FROM submissions WHERE user_id = $1 ORDER BY submitted_at DESC LIMIT $3 OFFSET $2
`

type ListSubmissionsByUserParams struct {
	UserID    int64 `json:"user_id"`
	OffsetVal int32 `json:"offset_val"`
	LimitVal  int32 `json:"limit_val"`
}

func (q *Queries) ListSubmissionsByUser(ctx context.Context, arg ListSubmissionsByUserParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByUser, arg.UserID, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.Language,
			&i.SourceCode,
			&i.SubmittedAt,
			&i.Status,
			&i.Verdict,
			&i.CompileOutput,
			&i.TimeMs,
			&i.MemoryKb,
			&i.CodeSize,
			&i.RunAllTests,
			&i.JudgeNodeID,
			&i.Attempts,
			&i.ContestID,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByUserAndProblem = `-- name: ListSubmissionsByUserAndProblem :many
SELECT id, user_id, problem_id, language, source_code, submitted_at, status, verdict, compile_output, time_ms, memory_kb, code_size, run_all_tests, judge_node_id, attempts, contest_id, score FROM submissions WHERE user_id = $1 AND problem_id = $2 ORDER BY submitted_at DESC LIMIT $4 OFFSET $3
`

type ListSubmissionsByUserAndProblemParams struct {
	UserID    int64 `json:"user_id"`
	ProblemID int64 `json:"problem_id"`
	OffsetVal int32 `json:"offset_val"`
	LimitVal  int32 `json:"limit_val"`
}

func (q *Queries) ListSubmissionsByUserAndProblem(ctx context.Context, arg ListSubmissionsByUserAndProblemParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByUserAndProblem,
		arg.UserID,
		arg.ProblemID,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.Language,
			&i.SourceCode,
			&i.SubmittedAt,
			&i.Status,
			&i.Verdict,
			&i.CompileOutput,
			&i.TimeMs,
			&i.MemoryKb,
			&i.CodeSize,
			&i.RunAllTests,
			&i.JudgeNodeID,
			&i.Attempts,
			&i.ContestID,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueSubmission = `-- name: RequeueSubmission :exec
UPDATE submissions SET status = 'queued' WHERE id = $1
`

func (q *Queries) RequeueSubmission(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, requeueSubmission, id)
	return err
}

const updateSubmissionFailed = `-- name: UpdateSubmissionFailed :exec
UPDATE submissions SET status = 'failed', verdict = 'SYSTEM_ERROR', compile_output = $2 WHERE id = $1
`

type UpdateSubmissionFailedParams struct {
	ID            int64  `json:"id"`
	CompileOutput string `json:"compile_output"`
}

func (q *Queries) UpdateSubmissionFailed(ctx context.Context, arg UpdateSubmissionFailedParams) error {
	_, err := q.db.Exec(ctx, updateSubmissionFailed, arg.ID, arg.CompileOutput)
	return err
}

const updateSubmissionJudging = `-- name: UpdateSubmissionJudging :exec
UPDATE submissions SET status = 'judging', judge_node_id = $2 WHERE id = $1
`

type UpdateSubmissionJudgingParams struct {
	ID          int64  `json:"id"`
	JudgeNodeID *int64 `json:"judge_node_id"`
}

func (q *Queries) UpdateSubmissionJudging(ctx context.Context, arg UpdateSubmissionJudgingParams) error {
	_, err := q.db.Exec(ctx, updateSubmissionJudging, arg.ID, arg.JudgeNodeID)
	return err
}

const updateSubmissionResult = `-- name: UpdateSubmissionResult :exec
UPDATE submissions SET status = 'done', verdict = $2, time_ms = $3, memory_kb = $4, compile_output = $5, score = CASE WHEN CAST($2 AS varchar) = 'AC' THEN 100 ELSE 0 END WHERE id = $1
`

type UpdateSubmissionResultParams struct {
	ID            int64  `json:"id"`
	Verdict       string `json:"verdict"`
	TimeMs        int32  `json:"time_ms"`
	MemoryKb      int32  `json:"memory_kb"`
	CompileOutput string `json:"compile_output"`
}

func (q *Queries) UpdateSubmissionResult(ctx context.Context, arg UpdateSubmissionResultParams) error {
	_, err := q.db.Exec(ctx, updateSubmissionResult,
		arg.ID,
		arg.Verdict,
		arg.TimeMs,
		arg.MemoryKb,
		arg.CompileOutput,
	)
	return err
}

const updateSubmissionStatus = `-- name: UpdateSubmissionStatus :exec
UPDATE submissions SET status = $2 WHERE id = $1
`

type UpdateSubmissionStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateSubmissionStatus(ctx context.Context, arg UpdateSubmissionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubmissionStatus, arg.ID, arg.Status)
	return err
}
