// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subtasks.sql

package sqlcdb

import (
	"context"
)

const createSubtask = `-- name: CreateSubtask :one
INSERT INTO subtasks (problem_id, subtask_index, points, description)
VALUES ($1, $2, $3, $4)
RETURNING id, problem_id, subtask_index, points, description
`

type CreateSubtaskParams struct {
	ProblemID    int64  `json:"problem_id"`
	SubtaskIndex int32  `json:"subtask_index"`
	Points       int32  `json:"points"`
	Description  string `json:"description"`
}

func (q *Queries) CreateSubtask(ctx context.Context, arg CreateSubtaskParams) (Subtask, error) {
	row := q.db.QueryRow(ctx, createSubtask,
		arg.ProblemID,
		arg.SubtaskIndex,
		arg.Points,
		arg.Description,
	)
	var i Subtask
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.SubtaskIndex,
		&i.Points,
		&i.Description,
	)
	return i, err
}

const deleteSubtask = `-- name: DeleteSubtask :exec
DELETE FROM subtasks WHERE id = $1
`

func (q *Queries) DeleteSubtask(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSubtask, id)
	return err
}

const listSubtasksByProblem = `-- name: ListSubtasksByProblem :many
SELECT id, problem_id, subtask_index, points, description FROM subtasks WHERE problem_id = $1 ORDER BY subtask_index
`

func (q *Queries) ListSubtasksByProblem(ctx context.Context, problemID int64) ([]Subtask, error) {
	rows, err := q.db.Query(ctx, listSubtasksByProblem, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subtask{}
	for rows.Next() {
		var i Subtask
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.SubtaskIndex,
			&i.Points,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
