// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: test_cases.sql

package sqlcdb

import (
	"context"
)

const createTestCase = `-- name: CreateTestCase :one
INSERT INTO test_cases (problem_id, order_index, input, expected_output, is_sample, subtask_id, description)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, problem_id, order_index, input, expected_output, is_sample, subtask_id, description
`

type CreateTestCaseParams struct {
	ProblemID      int64   `json:"problem_id"`
	OrderIndex     int32   `json:"order_index"`
	Input          string  `json:"input"`
	ExpectedOutput string  `json:"expected_output"`
	IsSample       bool    `json:"is_sample"`
	SubtaskID      *int64  `json:"subtask_id"`
	Description    *string `json:"description"`
}

func (q *Queries) CreateTestCase(ctx context.Context, arg CreateTestCaseParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, createTestCase,
		arg.ProblemID,
		arg.OrderIndex,
		arg.Input,
		arg.ExpectedOutput,
		arg.IsSample,
		arg.SubtaskID,
		arg.Description,
	)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.OrderIndex,
		&i.Input,
		&i.ExpectedOutput,
		&i.IsSample,
		&i.SubtaskID,
		&i.Description,
	)
	return i, err
}

const deleteTestCase = `-- name: DeleteTestCase :exec
DELETE FROM test_cases WHERE id = $1
`

func (q *Queries) DeleteTestCase(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTestCase, id)
	return err
}

const deleteTestCasesByProblem = `-- name: DeleteTestCasesByProblem :exec
DELETE FROM test_cases WHERE problem_id = $1
`

func (q *Queries) DeleteTestCasesByProblem(ctx context.Context, problemID int64) error {
	_, err := q.db.Exec(ctx, deleteTestCasesByProblem, problemID)
	return err
}

const getSampleTestCases = `-- name: GetSampleTestCases :many
SELECT id, problem_id, order_index, input, expected_output, is_sample, subtask_id, description FROM test_cases WHERE problem_id = $1 AND is_sample = true ORDER BY order_index
`

func (q *Queries) GetSampleTestCases(ctx context.Context, problemID int64) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, getSampleTestCases, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestCase{}
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.OrderIndex,
			&i.Input,
			&i.ExpectedOutput,
			&i.IsSample,
			&i.SubtaskID,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCasesByProblem = `-- name: ListTestCasesByProblem :many
SELECT id, problem_id, order_index, input, expected_output, is_sample, subtask_id, description FROM test_cases WHERE problem_id = $1 ORDER BY order_index
`

func (q *Queries) ListTestCasesByProblem(ctx context.Context, problemID int64) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, listTestCasesByProblem, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestCase{}
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.OrderIndex,
			&i.Input,
			&i.ExpectedOutput,
			&i.IsSample,
			&i.SubtaskID,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderTestCase = `-- name: ReorderTestCase :exec
UPDATE test_cases SET order_index = $2 WHERE id = $1
`

type ReorderTestCaseParams struct {
	ID         int64 `json:"id"`
	OrderIndex int32 `json:"order_index"`
}

func (q *Queries) ReorderTestCase(ctx context.Context, arg ReorderTestCaseParams) error {
	_, err := q.db.Exec(ctx, reorderTestCase, arg.ID, arg.OrderIndex)
	return err
}

const updateTestCase = `-- name: UpdateTestCase :exec
UPDATE test_cases SET input = $2, expected_output = $3, is_sample = $4, subtask_id = $5, order_index = $6, description = $7 WHERE id = $1
`

type UpdateTestCaseParams struct {
	ID             int64   `json:"id"`
	Input          string  `json:"input"`
	ExpectedOutput string  `json:"expected_output"`
	IsSample       bool    `json:"is_sample"`
	SubtaskID      *int64  `json:"subtask_id"`
	OrderIndex     int32   `json:"order_index"`
	Description    *string `json:"description"`
}

func (q *Queries) UpdateTestCase(ctx context.Context, arg UpdateTestCaseParams) error {
	_, err := q.db.Exec(ctx, updateTestCase,
		arg.ID,
		arg.Input,
		arg.ExpectedOutput,
		arg.IsSample,
		arg.SubtaskID,
		arg.OrderIndex,
		arg.Description,
	)
	return err
}
